export const ADD_CARD = 'ADD_CARD';
export const DELETE_CARD = 'DELETE_CARD';
export const CHANGE_CARD_NAME = 'CHANGE_CARD_NAME';
export const CHANGE_CARD_DESCRIPTION = 'CHANGE_CARD_DESCRIPTION';

export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const CHANGE_COMMENT = 'CHANGE_COMMENT';

export const CHANGE_COLUMN_TITLE = 'CHANGE_COLUMN_TITLE';
